name: Create Github Release

on:
  push:
    branches: [ main ]

permissions: write-all
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'sbt'

      - name: Set version variable
        run: | 
          echo "VERSION_NAME=$(sbt -Dsbt.supershell=false -no-colors -error 'print version')" >> $GITHUB_ENV
          echo Version found ${{env.VERSION_NAME}}
          
      - name: Building package with Sbt [${{env.VERSION_NAME}}]
        run: |
          sbt clean compile assembly
          
      - name: Create release (only non-snapshot versions)
        if: ${{ !endsWith(env.VERSION_NAME, '-SNAPSHOT') }}
        run: |
          if [ $(git tag -l "v${{env.VERSION_NAME}}") ]; then echo "Tag v${{env.VERSION_NAME}} already released"; exit 1; fi
          gh release create v${{env.VERSION_NAME}} -t v${{env.VERSION_NAME}} target/scala-2.13/s3-cloudsearch-lambda_2.13-${{env.VERSION_NAME}}.jar --latest --generate-notes
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
